version: '3.7'
services:

  api-gateway:
    image: younghub/05-api-gateway-server:0.0.1-SNAPSHOP
    build:
      context: 05-api-gateway-server
      dockerfile: Dockerfile
    container_name: api-gateway-server
    ports:
      - "8765:8765"
    restart: always
    depends_on:
      - eureka-server
      - rabbitmq
      - zipkin-server
    environment:
      SERVICE_URL_DEFAULT_ZONE: http://eureka-server:8761/eureka
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans
    networks:
      currency-network:

  eureka-server:
    image: younghub/05-netflix-eureka-naming-server:0.0.1-SNAPSHOP
    build:
      context: 05-netflix-eureka-naming-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: always
    networks:
      currency-network:

  currency-exchange:
    image: younghub/05-currency-exchange-service:0.0.1-SNAPSHOP
    build:
      context: 05-currency-exchange-service
      dockerfile: Dockerfile
    container_name: currency-exchange-con
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - eureka-server
      - rabbitmq
    environment:
      SERVICE_URL_DEFAULT_ZONE: http://eureka-server:8761/eureka
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans
    networks:
      currency-network:



  currency-conversion:
    image: younghub/05-currency-conversion-service:0.0.1-SNAPSHOP
    build:
      context: 05-currency-conversion-service
      dockerfile: Dockerfile
    container_name: currency-conversion-con
    ports:
      - "8100:8100"
    restart: always
    depends_on:
      - currency-exchange
      - eureka-server
      - rabbitmq
      - zipkin-server
    environment:
      #      CURRENCY_EXCHANGE_URI: http://currency-exchange:8000
      SERVICE_URL_DEFAULT_ZONE: http://eureka-server:8761/eureka
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans
    networks:
      currency-network:

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    mem_limit: 800m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      currency-network:

  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin
    mem_limit: 1g
    ports:
      - "9411:9411"
    environment:
      STORAGE_TYPE: mem
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: always
    networks:
      currency-network:





networks:
  currency-network: