package com.apple.laf.resources;

import java.util.ListResourceBundle;

public final class aqua_de extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "AbstractButton.click.textAndMnemonic", "Klicken" },
            { "AbstractDocument.addition.textAndMnemonic", "Hinzuf\u00FCgen" },
            { "AbstractDocument.deletion.textAndMnemonic", "L\u00F6schen" },
            { "AbstractDocument.redo.textAndMnemonic", "Wiederherstellen" },
            { "AbstractDocument.styleChange.textAndMnemonic", "Formatvorlagen\u00E4nderung" },
            { "AbstractDocument.undo.textAndMnemonic", "R\u00FCckg\u00E4ngig" },
            { "AbstractUndoableEdit.redo.textAndMnemonic", "Wiederherstellen" },
            { "AbstractUndoableEdit.undo.textAndMnemonic", "R\u00FCckg\u00E4ngig" },
            { "ColorChooser.cancel.textAndMnemonic", "Abbrechen" },
            { "ColorChooser.hsb.textAndMnemonic", "&HSB" },
            { "ColorChooser.hsbBlue.textAndMnemonic", "B" },
            { "ColorChooser.hsbBrightness.textAndMnemonic", "B" },
            { "ColorChooser.hsbGreen.textAndMnemonic", "G" },
            { "ColorChooser.hsbHue.textAndMnemonic", "H" },
            { "ColorChooser.hsbRed.textAndMnemonic", "R" },
            { "ColorChooser.hsbSaturation.textAndMnemonic", "S" },
            { "ColorChooser.ok.textAndMnemonic", "OK" },
            { "ColorChooser.preview.textAndMnemonic", "Vorschau" },
            { "ColorChooser.reset.textAndMnemonic", "&Zur\u00FCcksetzen" },
            { "ColorChooser.rgb.textAndMnemonic", "R&GB" },
            { "ColorChooser.rgbBlue.textAndMnemonic", "&Blau" },
            { "ColorChooser.rgbGreen.textAndMnemonic", "Gr\u00FC&n" },
            { "ColorChooser.rgbRed.textAndMnemonic", "Ro&t" },
            { "ColorChooser.sample.textAndMnemonic", "Beispieltext  Beispieltext" },
            { "ColorChooser.swatches.textAndMnemonic", "&Muster" },
            { "ColorChooser.swatchesRecent.textAndMnemonic", "Aktuell:" },
            { "ComboBox.togglePopup.textAndMnemonic", "togglePopup" },
            { "FileChooser.acceptAllFileFilter.textAndMnemonic", "Alle Dateien" },
            { "FileChooser.by.textAndMnemonic", "Name" },
            { "FileChooser.byDate.textAndMnemonic", "\u00C4nderungsdatum" },
            { "FileChooser.cancelButton.textAndMnemonic", "Abbrechen" },
            { "FileChooser.chooseButton.textAndMnemonic", "W\u00E4hlen" },
            { "FileChooser.createButton.textAndMnemonic", "Erstellen" },
            { "FileChooser.desktopName", "Desktop" },
            { "FileChooser.directoryDescription.textAndMnemonic", "Verzeichnis" },
            { "FileChooser.directoryOpenButton.textAndMnemonic", "\u00D6ffnen" },
            { "FileChooser.fileDescription.textAndMnemonic", "Allgemeine Datei" },
            { "FileChooser.fileNameLabel.textAndMnemonic", "Datei:" },
            { "FileChooser.fileSizeGigaBytes", "{0} GB" },
            { "FileChooser.fileSizeKiloBytes", "{0} KB" },
            { "FileChooser.fileSizeMegaBytes", "{0} MB" },
            { "FileChooser.filesOfTypeLabel.textAndMnemonic", "Dateiformat:" },
            { "FileChooser.helpButton.textAndMnemonic", "Hilfe" },
            { "FileChooser.mac.newFolder", "unbenannter Ordner" },
            { "FileChooser.mac.newFolder.subsequent", "unbenannter Ordner {0}" },
            { "FileChooser.newFolderAccessibleName", "Neuer Ordner" },
            { "FileChooser.newFolderButton.textAndMnemonic", "Neuer Ordner" },
            { "FileChooser.newFolderError.textAndMnemonic", "Bei der Erstellung des Ordners ist ein Fehler aufgetreten" },
            { "FileChooser.newFolderErrorSeparator", ":" },
            { "FileChooser.newFolderExistsError.textAndMnemonic", "Dieser Name ist bereits vergeben" },
            { "FileChooser.newFolderPrompt.textAndMnemonic", "Name des neuen Ordners:" },
            { "FileChooser.newFolderTitle.textAndMnemonic", "Neuer Ordner" },
            { "FileChooser.openButton.textAndMnemonic", "\u00D6ffnen" },
            { "FileChooser.openDialogTitle.textAndMnemonic", "\u00D6ffnen" },
            { "FileChooser.openTitle.textAndMnemonic", "\u00D6ffnen" },
            { "FileChooser.saveButton.textAndMnemonic", "Speichern" },
            { "FileChooser.saveDialogFileNameLabel.textAndMnemonic", "Speichern unter:" },
            { "FileChooser.saveDialogTitle.textAndMnemonic", "Speichern" },
            { "FileChooser.saveTitle.textAndMnemonic", "Speichern" },
            { "FileChooser.untitledFileName", "unbenannt" },
            { "FileChooser.untitledFolderName", "unbenannter Ordner" },
            { "FileChooser.updateButton.textAndMnemonic", "Aktualisieren" },
            { "FormView.browseFileButton.textAndMnemonic", "Durchsuchen..." },
            { "FormView.resetButton.textAndMnemonic", "Zur\u00FCcksetzen" },
            { "FormView.submitButton.textAndMnemonic", "Abfrage weiterleiten" },
            { "InternalFrame.closeButtonToolTip", "Schlie\u00DFen" },
            { "InternalFrame.iconButtonToolTip", "Minimieren" },
            { "InternalFrame.maxButtonToolTip", "Maximieren" },
            { "InternalFrame.restoreButtonToolTip", "Wiederherstellen" },
            { "InternalFrameTitlePane.closeButton.textAndMnemonic", "Schlie\u00DFen" },
            { "InternalFrameTitlePane.closeButtonAccessibleName", "Schlie\u00DFen" },
            { "InternalFrameTitlePane.iconifyButtonAccessibleName", "Als Symbol darstellen" },
            { "InternalFrameTitlePane.maximizeButton.textAndMnemonic", "Maximieren" },
            { "InternalFrameTitlePane.maximizeButtonAccessibleName", "Maximieren" },
            { "InternalFrameTitlePane.minimizeButton.textAndMnemonic", "Minimieren" },
            { "InternalFrameTitlePane.moveButton.textAndMnemonic", "Verschieben" },
            { "InternalFrameTitlePane.restoreButton.textAndMnemonic", "Wiederherstellen" },
            { "InternalFrameTitlePane.sizeButton.textAndMnemonic", "Gr\u00F6\u00DFe" },
            { "IsindexView.prompt", "Dieser Index kann durchsucht werden. Geben Sie Schl\u00FCsselw\u00F6rter f\u00FCr die Suche ein:" },
            { "OptionPane.cancelButton.textAndMnemonic", "Abbrechen" },
            { "OptionPane.inputDialog.titleAndMnemonic", "Eingabe" },
            { "OptionPane.messageDialog.titleAndMnemonic", "Meldung" },
            { "OptionPane.noButton.textAndMnemonic", "&Nein" },
            { "OptionPane.okButton.textAndMnemonic", "OK" },
            { "OptionPane.title.textAndMnemonic", "Option ausw\u00E4hlen" },
            { "OptionPane.yesButton.textAndMnemonic", "&Ja" },
            { "PrintingDialog.abortButton.textAndMnemonic", "&Abbruch" },
            { "PrintingDialog.abortButtonToolTip.textAndMnemonic", "Druckvorgang abbrechen" },
            { "PrintingDialog.contentAborting.textAndMnemonic", "Druckvorgang wird abgebrochen..." },
            { "PrintingDialog.contentInitial.textAndMnemonic", "Druckvorgang l\u00E4uft..." },
            { "PrintingDialog.contentProgress.textAndMnemonic", "Seite {0} wurde gedruckt..." },
            { "PrintingDialog.titleAborting.textAndMnemonic", "Drucken (wird abgebrochen)" },
            { "PrintingDialog.titleProgress.textAndMnemonic", "Drucken" },
            { "ProgressMonitor.progress.textAndMnemonic", "Fortschritt..." },
            { "SplitPane.leftButton.textAndMnemonic", "linke Schaltfl\u00E4che" },
            { "SplitPane.rightButton.textAndMnemonic", "rechte Schaltfl\u00E4che" },
        };
    }
}
