version: '3.7'

services:

  currency-exchange:
    image: younghub/micro-v3-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      SERVICE_URL_DEFAULT_ZONE: http://naming-server:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      #      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - currency-network

  currency-conversion:
    image: younghub/micro-v3-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 5g
    ports:
      - "8100:8100"
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  api-gateway:
    image: younghub/micro-v3-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 3g
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      SERVICE_URL_DEFAULT_ZONE: http://naming-server:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      currency-network:

  naming-server:
    image: younghub/micro-v3-netflix-eureka-naming-server:0.0.1-SNAPSHOT
    mem_limit: 1g
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin
    mem_limit: 1g
    ports:
      - "9411:9411"
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    mem_limit: 800m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      currency-network:

networks:
  currency-network: