package sun.awt.resources;

import java.util.ListResourceBundle;

public final class awtosx extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "AWT.Less", "<" },
            { "AWT.add", "\u2328 +" },
            { "AWT.alt", "\u2325" },
            { "AWT.altGraph", "\u2325" },
            { "AWT.ampersand", "&" },
            { "AWT.asterisk", "*" },
            { "AWT.at", "@" },
            { "AWT.backQuote", "`" },
            { "AWT.backSlash", "\\" },
            { "AWT.backSpace", "\u232B" },
            { "AWT.braceLeft", "[" },
            { "AWT.braceRight", "]" },
            { "AWT.cancel", "\u238B" },
            { "AWT.capsLock", "\u21EA" },
            { "AWT.circumflex", "^" },
            { "AWT.clear", "\u2327" },
            { "AWT.closeBracket", "]" },
            { "AWT.colon", ":" },
            { "AWT.comma", "," },
            { "AWT.control", "\u2303" },
            { "AWT.decimal", "\u2328 ." },
            { "AWT.delete", "\u2326" },
            { "AWT.divide", "\u2328 /" },
            { "AWT.dollar", "$" },
            { "AWT.down", "\u2193" },
            { "AWT.end", "\u2198" },
            { "AWT.enter", "\u23CE" },
            { "AWT.equals", "=" },
            { "AWT.escape", "\u238B" },
            { "AWT.euro", "\u20AC" },
            { "AWT.exclamationMark", "!" },
            { "AWT.greater", ">" },
            { "AWT.home", "\u2196" },
            { "AWT.invertedExclamationMark", "\u00A1" },
            { "AWT.left", "\u2190" },
            { "AWT.leftParenthesis", "(" },
            { "AWT.meta", "\u2318" },
            { "AWT.minus", "-" },
            { "AWT.multiply", "\u2328 *" },
            { "AWT.numberSign", "#" },
            { "AWT.numpad", "\u2328" },
            { "AWT.openBracket", "[" },
            { "AWT.period", "." },
            { "AWT.pgdn", "\u21DF" },
            { "AWT.pgup", "\u21DE" },
            { "AWT.plus", "+" },
            { "AWT.printScreen", "\u2399" },
            { "AWT.quote", "'" },
            { "AWT.quoteDbl", "\"" },
            { "AWT.right", "\u2192" },
            { "AWT.rightParenthesis", ")" },
            { "AWT.semicolon", ";" },
            { "AWT.separater", "\u2328 ," },
            { "AWT.separator", "\u2328 ," },
            { "AWT.shift", "\u21E7" },
            { "AWT.slash", "/" },
            { "AWT.space", "\u2423" },
            { "AWT.subtract", "\u2328 -" },
            { "AWT.tab", "\u21E5" },
            { "AWT.underscore", "_" },
            { "AWT.up", "\u2191" },
        };
    }
}
